### ISSUE TITLE
Not processing files (Status 3)

### ISSUE THREAD

**Issue by epicylon** [cmccambridge/ocrmypdf-auto#16] opened 2020-08-09 20:35 UTC
Hello, I've set up my container with the following parameters

```
    docker create \
  --name=ocrmypdf-auto \
  -v /srv/faa137b2-b75f-42c4-a777-497ac74524ef/altered/ocr/input:/input \
  -v /srv/faa137b2-b75f-42c4-a777-497ac74524ef/altered/ocr/output:/output \
  -v /srv/dev-disk-by-label-fsb/altered/appdata/ocrmypdf_auto:/config \
  -v /srv/faa137b2-b75f-42c4-a777-497ac74524ef/altered/ocr/temp:/ocrtemp \
  -v /srv/faa137b2-b75f-42c4-a777-497ac74524ef/altered/ocr/archive:/archive \
  -e OCR_LANGUAGES="nor chi-sim dan eng swe" \
  -e OCR_OUTPUT_MODE=MIRROR_TREE \
  -e OCR_PROCESS_EXISTING_ON_START=1 \
  -e OCR_ACTION_ON_SUCCESS=DELETE_INPUT_FILES \
  -e PUID=1000 \
  -e PGID=100 \
  -e UMASK_SET=000 \
  quay.io/cmccambridge/ocrmypdf-auto
```

In the portainer logs I get the following (error?)

```
2020-08-09 20:31:52 - Watching /input,
2020-08-09 20:31:52 - Processing: /input/Scan-037.pdf -> /output/Scan-037.pdf,
2020-08-09 20:31:52 - Processing: /input/._Scan-037.pdf -> /output/._Scan-037.pdf,
2020-08-09 20:31:55 - Processing complete in 3.350000 seconds with status 3: /input/._Scan-037.pdf,
TESTOCR_PROCESS_RESULT/input/._Scan-037.pdf/output/._Scan-037.pdf33.350000,
2020-08-09 20:31:55 - Processing complete in 3.350000 seconds with status 3: /input/Scan-037.pdf,
TESTOCR_PROCESS_RESULT/input/Scan-037.pdf/output/Scan-037.pdf33.350000

```
The input files stays in the input folder and are not deleted as I set them up to be. Output folder is empty. 

I've tried resetting folder permissions to no avail.

**Comment by cmccambridge** [comment] 2020-12-05 02:52
Hi @epicylon - Extremely late response here, apologies. If this is still an error you're encountering and want to try and resolve, please let me know.

I have recently updated the container to the latest OCRmyPDF upstream release (many versions newer than what this container contained in August). If you'd like to try that, please pull the `latest` tag again.

Status `3` in this case corresponds to OCRmyPDF reporting that a required external program is missing. This is rather surprising in a docker container since I should have everything properly preinstalled. If you're able to reproduce this, I would be happy to try and dig in deeper.

The input files remaining in the input folder and the output folder being empty is consistent with this missing dependency error. If OCR is not completed successfully, the automation script will not perform the post-processing actions.

**Comment by schwabelbauch** [comment] 2020-12-05 07:13
Had exactly the same issue.
After updating this issue is fixed for me, thanks!

**Comment by cmccambridge** [comment] 2020-12-05 15:43
Good to hear @schwabelbauch!

**Comment by cmccambridge** [comment] 2021-01-23 04:20
I'm going to go ahead and close this issue out, but please feel free to reopen it if you're still encountering issues @epicylon. Hopefully an update to the latest version will resolve it!

**Closed by cmccambridge** 2021-01-23 04:20 UTC
